### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by armanbilge** [gemini-hlsw/lucuma-react#24]
- [ ] https://github.com/gemini-hlsw/lucuma-react/pull/7
- [ ] https://github.com/rpiaggio/scalajs-react-hotkeys
- [ ] https://github.com/cquiroz/scalajs-react-resizable
